# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(884, 493)
        MainWindow.setMinimumSize(QtCore.QSize(800, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(10, 20, 889, 449))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_filters = QtWidgets.QWidget()
        self.tab_filters.setObjectName("tab_filters")
        self.label_filters_input = QtWidgets.QLabel(self.tab_filters)
        self.label_filters_input.setGeometry(QtCore.QRect(180, 30, 331, 231))
        self.label_filters_input.setFrameShape(QtWidgets.QFrame.Box)
        self.label_filters_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_filters_input.setObjectName("label_filters_input")
        self.label_filters_output = QtWidgets.QLabel(self.tab_filters)
        self.label_filters_output.setGeometry(QtCore.QRect(520, 30, 331, 231))
        self.label_filters_output.setFrameShape(QtWidgets.QFrame.Box)
        self.label_filters_output.setTextFormat(QtCore.Qt.PlainText)
        self.label_filters_output.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_filters_output.setObjectName("label_filters_output")
        self.pushButton_filters_load = QtWidgets.QPushButton(self.tab_filters)
        self.pushButton_filters_load.setGeometry(QtCore.QRect(20, 30, 121, 81))
        self.pushButton_filters_load.setObjectName("pushButton_filters_load")
        self.label = QtWidgets.QLabel(self.tab_filters)
        self.label.setGeometry(QtCore.QRect(30, 140, 71, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_filters)
        self.label_2.setGeometry(QtCore.QRect(30, 170, 71, 21))
        self.label_2.setObjectName("label_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_filters)
        self.groupBox.setGeometry(QtCore.QRect(30, 280, 751, 111))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 40, 311, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.comboBox_filters = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_filters.setObjectName("comboBox_filters")
        self.comboBox_filters.addItem("")
        self.comboBox_filters.addItem("")
        self.comboBox_filters.addItem("")
        self.comboBox_filters.addItem("")
        self.comboBox_filters.addItem("")
        self.comboBox_filters.addItem("")
        self.comboBox_filters.addItem("")
        self.comboBox_filters.addItem("")
        self.comboBox_filters.addItem("")
        self.comboBox_filters.addItem("")
        self.comboBox_filters.addItem("")
        self.comboBox_filters.addItem("")
        self.comboBox_filters.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_filters)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(380, 30, 311, 71))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 88, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.spinBox_filter_size = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_filter_size.setMinimum(3)
        self.spinBox_filter_size.setMaximum(51)
        self.spinBox_filter_size.setSingleStep(2)
        self.spinBox_filter_size.setObjectName("spinBox_filter_size")
        self.horizontalLayout_5.addWidget(self.spinBox_filter_size)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 40, 88, 22))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.doubleSpinBox_sigma = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.doubleSpinBox_sigma.setObjectName("doubleSpinBox_sigma")
        self.horizontalLayout_4.addWidget(self.doubleSpinBox_sigma)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(160, 40, 75, 22))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.doubleSpinBox_mu = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        self.doubleSpinBox_mu.setObjectName("doubleSpinBox_mu")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_mu)
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget3.setGeometry(QtCore.QRect(160, 20, 77, 22))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.doubleSpinBox_low = QtWidgets.QDoubleSpinBox(self.layoutWidget3)
        self.doubleSpinBox_low.setMaximum(1.0)
        self.doubleSpinBox_low.setSingleStep(0.01)
        self.doubleSpinBox_low.setObjectName("doubleSpinBox_low")
        self.horizontalLayout_2.addWidget(self.doubleSpinBox_low)
        self.tabWidget.addTab(self.tab_filters, "")
        self.tab_histograms = QtWidgets.QWidget()
        self.tab_histograms.setObjectName("tab_histograms")
        self.label_histograms_houtput = QtWidgets.QLabel(self.tab_histograms)
        self.label_histograms_houtput.setGeometry(QtCore.QRect(450, 200, 261, 191))
        self.label_histograms_houtput.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_houtput.setTextFormat(QtCore.Qt.PlainText)
        self.label_histograms_houtput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_houtput.setObjectName("label_histograms_houtput")
        self.pushButton_histograms_load = QtWidgets.QPushButton(self.tab_histograms)
        self.pushButton_histograms_load.setGeometry(QtCore.QRect(40, 20, 121, 81))
        self.pushButton_histograms_load.setObjectName("pushButton_histograms_load")
        self.label_histograms_input = QtWidgets.QLabel(self.tab_histograms)
        self.label_histograms_input.setGeometry(QtCore.QRect(200, 20, 241, 171))
        self.label_histograms_input.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_input.setObjectName("label_histograms_input")
        self.label_histograms_output = QtWidgets.QLabel(self.tab_histograms)
        self.label_histograms_output.setGeometry(QtCore.QRect(450, 20, 261, 171))
        self.label_histograms_output.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_output.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_output.setObjectName("label_histograms_output")
        self.label_10 = QtWidgets.QLabel(self.tab_histograms)
        self.label_10.setGeometry(QtCore.QRect(50, 160, 71, 21))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_histograms)
        self.label_11.setGeometry(QtCore.QRect(50, 130, 71, 21))
        self.label_11.setObjectName("label_11")
        self.label_histograms_hinput = QtWidgets.QLabel(self.tab_histograms)
        self.label_histograms_hinput.setGeometry(QtCore.QRect(200, 200, 241, 191))
        self.label_histograms_hinput.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_hinput.setTextFormat(QtCore.Qt.PlainText)
        self.label_histograms_hinput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_hinput.setObjectName("label_histograms_hinput")
        self.pushButton_Auto_global_thershold = QtWidgets.QPushButton(self.tab_histograms)
        self.pushButton_Auto_global_thershold.setGeometry(QtCore.QRect(40, 200, 131, 23))
        self.pushButton_Auto_global_thershold.setObjectName("pushButton_Auto_global_thershold")
        self.pushButton_globalThershold = QtWidgets.QPushButton(self.tab_histograms)
        self.pushButton_globalThershold.setGeometry(QtCore.QRect(40, 240, 131, 23))
        self.pushButton_globalThershold.setObjectName("pushButton_globalThershold")
        self.pushButton_local_thershold = QtWidgets.QPushButton(self.tab_histograms)
        self.pushButton_local_thershold.setGeometry(QtCore.QRect(40, 350, 131, 23))
        self.pushButton_local_thershold.setObjectName("pushButton_local_thershold")
        self.doubleSpinBox_Thershold_value = QtWidgets.QDoubleSpinBox(self.tab_histograms)
        self.doubleSpinBox_Thershold_value.setGeometry(QtCore.QRect(110, 270, 62, 22))
        self.doubleSpinBox_Thershold_value.setMaximum(1.0)
        self.doubleSpinBox_Thershold_value.setSingleStep(0.01)
        self.doubleSpinBox_Thershold_value.setProperty("value", 0.5)
        self.doubleSpinBox_Thershold_value.setObjectName("doubleSpinBox_Thershold_value")
        self.comboBox_thersholding_filter = QtWidgets.QComboBox(self.tab_histograms)
        self.comboBox_thersholding_filter.setGeometry(QtCore.QRect(100, 380, 69, 22))
        self.comboBox_thersholding_filter.setObjectName("comboBox_thersholding_filter")
        self.comboBox_thersholding_filter.addItem("")
        self.comboBox_thersholding_filter.addItem("")
        self.comboBox_thersholding_filter.addItem("")
        self.spinBox_thershlod_filter_size = QtWidgets.QSpinBox(self.tab_histograms)
        self.spinBox_thershlod_filter_size.setGeometry(QtCore.QRect(40, 380, 42, 22))
        self.spinBox_thershlod_filter_size.setMinimum(3)
        self.spinBox_thershlod_filter_size.setMaximum(41)
        self.spinBox_thershlod_filter_size.setSingleStep(2)
        self.spinBox_thershlod_filter_size.setProperty("value", 7)
        self.spinBox_thershlod_filter_size.setObjectName("spinBox_thershlod_filter_size")
        self.tabWidget.addTab(self.tab_histograms, "")
        self.tab_hybrid = QtWidgets.QWidget()
        self.tab_hybrid.setObjectName("tab_hybrid")
        self.label_histograms_input_2 = QtWidgets.QLabel(self.tab_hybrid)
        self.label_histograms_input_2.setGeometry(QtCore.QRect(180, 20, 241, 171))
        self.label_histograms_input_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_input_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_input_2.setObjectName("label_histograms_input_2")
        self.label_histograms_hinput_2 = QtWidgets.QLabel(self.tab_hybrid)
        self.label_histograms_hinput_2.setGeometry(QtCore.QRect(180, 200, 241, 191))
        self.label_histograms_hinput_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_hinput_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_histograms_hinput_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_hinput_2.setObjectName("label_histograms_hinput_2")
        self.label_histograms_output_2 = QtWidgets.QLabel(self.tab_hybrid)
        self.label_histograms_output_2.setGeometry(QtCore.QRect(430, 20, 431, 371))
        self.label_histograms_output_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_output_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_output_2.setObjectName("label_histograms_output_2")
        self.label_12 = QtWidgets.QLabel(self.tab_hybrid)
        self.label_12.setGeometry(QtCore.QRect(30, 110, 71, 21))
        self.label_12.setObjectName("label_12")
        self.pushButton_histograms_load_2 = QtWidgets.QPushButton(self.tab_hybrid)
        self.pushButton_histograms_load_2.setGeometry(QtCore.QRect(20, 20, 121, 81))
        self.pushButton_histograms_load_2.setObjectName("pushButton_histograms_load_2")
        self.label_13 = QtWidgets.QLabel(self.tab_hybrid)
        self.label_13.setGeometry(QtCore.QRect(30, 130, 71, 21))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_hybrid)
        self.label_14.setGeometry(QtCore.QRect(30, 280, 71, 21))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab_hybrid)
        self.label_15.setGeometry(QtCore.QRect(30, 260, 71, 21))
        self.label_15.setObjectName("label_15")
        self.pushButton_histograms_load_3 = QtWidgets.QPushButton(self.tab_hybrid)
        self.pushButton_histograms_load_3.setGeometry(QtCore.QRect(20, 170, 121, 81))
        self.pushButton_histograms_load_3.setObjectName("pushButton_histograms_load_3")
        self.pushButton_histograms_load_4 = QtWidgets.QPushButton(self.tab_hybrid)
        self.pushButton_histograms_load_4.setGeometry(QtCore.QRect(20, 350, 121, 41))
        self.pushButton_histograms_load_4.setObjectName("pushButton_histograms_load_4")
        self.layoutWidget4 = QtWidgets.QWidget(self.tab_hybrid)
        self.layoutWidget4.setGeometry(QtCore.QRect(30, 320, 88, 22))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.doubleSpinBox_alpha = QtWidgets.QDoubleSpinBox(self.layoutWidget4)
        self.doubleSpinBox_alpha.setMinimum(0.1)
        self.doubleSpinBox_alpha.setMaximum(0.9)
        self.doubleSpinBox_alpha.setSingleStep(0.05)
        self.doubleSpinBox_alpha.setProperty("value", 0.5)
        self.doubleSpinBox_alpha.setObjectName("doubleSpinBox_alpha")
        self.horizontalLayout_6.addWidget(self.doubleSpinBox_alpha)
        self.tabWidget.addTab(self.tab_hybrid, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 884, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_filters_input.setText(_translate("MainWindow", "Input image"))
        self.label_filters_output.setText(_translate("MainWindow", "Output image"))
        self.pushButton_filters_load.setText(_translate("MainWindow", "Load Image"))
        self.label.setText(_translate("MainWindow", "Name:"))
        self.label_2.setText(_translate("MainWindow", "Size:"))
        self.groupBox.setTitle(_translate("MainWindow", "Filter Settings"))
        self.label_3.setText(_translate("MainWindow", "Select Filter"))
        self.comboBox_filters.setItemText(0, _translate("MainWindow", "Gaussian noise"))
        self.comboBox_filters.setItemText(1, _translate("MainWindow", "Uniform noise"))
        self.comboBox_filters.setItemText(2, _translate("MainWindow", "Salt & pepper noise"))
        self.comboBox_filters.setItemText(3, _translate("MainWindow", "ِGaussian filter"))
        self.comboBox_filters.setItemText(4, _translate("MainWindow", "Median filter"))
        self.comboBox_filters.setItemText(5, _translate("MainWindow", "Average"))
        self.comboBox_filters.setItemText(6, _translate("MainWindow", "Sobel"))
        self.comboBox_filters.setItemText(7, _translate("MainWindow", "Roberts"))
        self.comboBox_filters.setItemText(8, _translate("MainWindow", "Prewitt"))
        self.comboBox_filters.setItemText(9, _translate("MainWindow", "canny"))
        self.comboBox_filters.setItemText(10, _translate("MainWindow", "Laplacian of Gaussian"))
        self.comboBox_filters.setItemText(11, _translate("MainWindow", "Laplacian1"))
        self.comboBox_filters.setItemText(12, _translate("MainWindow", "Laplacian2"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Additional Parameters"))
        self.label_4.setText(_translate("MainWindow", "filter size"))
        self.label_5.setText(_translate("MainWindow", "sigma"))
        self.label_6.setText(_translate("MainWindow", "mu"))
        self.label_7.setText(_translate("MainWindow", "low"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_filters), _translate("MainWindow", "Filters"))
        self.label_histograms_houtput.setText(_translate("MainWindow", "Output Histogram"))
        self.pushButton_histograms_load.setText(_translate("MainWindow", "Load image"))
        self.label_histograms_input.setText(_translate("MainWindow", "Input image"))
        self.label_histograms_output.setText(_translate("MainWindow", "Output image"))
        self.label_10.setText(_translate("MainWindow", "Size:"))
        self.label_11.setText(_translate("MainWindow", "Name:"))
        self.label_histograms_hinput.setText(_translate("MainWindow", "Input Histogram"))
        self.pushButton_Auto_global_thershold.setText(_translate("MainWindow", "Auto Global Thersholding"))
        self.pushButton_globalThershold.setText(_translate("MainWindow", "Global Thersholding"))
        self.pushButton_local_thershold.setText(_translate("MainWindow", "Local Thersholding"))
        self.comboBox_thersholding_filter.setItemText(0, _translate("MainWindow", "Gaussian"))
        self.comboBox_thersholding_filter.setItemText(1, _translate("MainWindow", "Average"))
        self.comboBox_thersholding_filter.setItemText(2, _translate("MainWindow", "Median"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_histograms), _translate("MainWindow", "Histograms"))
        self.label_histograms_input_2.setText(_translate("MainWindow", "Input image A"))
        self.label_histograms_hinput_2.setText(_translate("MainWindow", "Input image B"))
        self.label_histograms_output_2.setText(_translate("MainWindow", "Output image"))
        self.label_12.setText(_translate("MainWindow", "Name:"))
        self.pushButton_histograms_load_2.setText(_translate("MainWindow", "Load image A"))
        self.label_13.setText(_translate("MainWindow", "Size:"))
        self.label_14.setText(_translate("MainWindow", "Size:"))
        self.label_15.setText(_translate("MainWindow", "Name:"))
        self.pushButton_histograms_load_3.setText(_translate("MainWindow", "Load image B"))
        self.pushButton_histograms_load_4.setText(_translate("MainWindow", "Make Hybrid"))
        self.label_8.setText(_translate("MainWindow", "Alpha"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_hybrid), _translate("MainWindow", "Hybrid"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

