# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1069, 739)
        MainWindow.setMinimumSize(QtCore.QSize(1069, 739))
        MainWindow.setMaximumSize(QtCore.QSize(1069, 739))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1051, 691))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_filters = QtWidgets.QWidget()
        self.tab_filters.setObjectName("tab_filters")
        self.groupBox = QtWidgets.QGroupBox(self.tab_filters)
        self.groupBox.setGeometry(QtCore.QRect(210, 410, 781, 141))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 40, 311, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.comboBox_filters = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_filters.setEnabled(False)
        self.comboBox_filters.setObjectName("comboBox_filters")
        self.comboBox_filters.addItem("")
        self.comboBox_filters.addItem("")
        self.comboBox_filters.addItem("")
        self.comboBox_filters.addItem("")
        self.comboBox_filters.addItem("")
        self.comboBox_filters.addItem("")
        self.comboBox_filters.addItem("")
        self.comboBox_filters.addItem("")
        self.comboBox_filters.addItem("")
        self.comboBox_filters.addItem("")
        self.comboBox_filters.addItem("")
        self.comboBox_filters.addItem("")
        self.comboBox_filters.addItem("")
        self.comboBox_filters.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_filters)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(390, 20, 371, 111))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 141, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.spinBox_filter_size = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_filter_size.setMinimum(3)
        self.spinBox_filter_size.setMaximum(51)
        self.spinBox_filter_size.setSingleStep(2)
        self.spinBox_filter_size.setObjectName("spinBox_filter_size")
        self.horizontalLayout_5.addWidget(self.spinBox_filter_size)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 70, 141, 31))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.doubleSpinBox_sigma = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.doubleSpinBox_sigma.setMinimum(0.01)
        self.doubleSpinBox_sigma.setMaximum(30.0)
        self.doubleSpinBox_sigma.setSingleStep(1.0)
        self.doubleSpinBox_sigma.setObjectName("doubleSpinBox_sigma")
        self.horizontalLayout_4.addWidget(self.doubleSpinBox_sigma)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(210, 70, 141, 31))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.doubleSpinBox_mu = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        self.doubleSpinBox_mu.setObjectName("doubleSpinBox_mu")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_mu)
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget3.setGeometry(QtCore.QRect(210, 30, 141, 31))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.doubleSpinBox_low = QtWidgets.QDoubleSpinBox(self.layoutWidget3)
        self.doubleSpinBox_low.setMaximum(1.0)
        self.doubleSpinBox_low.setSingleStep(0.01)
        self.doubleSpinBox_low.setProperty("value", 0.02)
        self.doubleSpinBox_low.setObjectName("doubleSpinBox_low")
        self.horizontalLayout_2.addWidget(self.doubleSpinBox_low)
        self.layoutWidget4 = QtWidgets.QWidget(self.tab_filters)
        self.layoutWidget4.setGeometry(QtCore.QRect(210, 20, 791, 361))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget4)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_filters_input = QtWidgets.QLabel(self.layoutWidget4)
        self.label_filters_input.setFrameShape(QtWidgets.QFrame.Box)
        self.label_filters_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_filters_input.setObjectName("label_filters_input")
        self.gridLayout_5.addWidget(self.label_filters_input, 0, 0, 1, 1)
        self.label_filters_output = QtWidgets.QLabel(self.layoutWidget4)
        self.label_filters_output.setFrameShape(QtWidgets.QFrame.Box)
        self.label_filters_output.setTextFormat(QtCore.Qt.PlainText)
        self.label_filters_output.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_filters_output.setObjectName("label_filters_output")
        self.gridLayout_5.addWidget(self.label_filters_output, 0, 1, 1, 1)
        self.splitter_4 = QtWidgets.QSplitter(self.tab_filters)
        self.splitter_4.setGeometry(QtCore.QRect(11, 141, 181, 161))
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.pushButton_filters_load = QtWidgets.QPushButton(self.splitter_4)
        self.pushButton_filters_load.setObjectName("pushButton_filters_load")
        self.label = QtWidgets.QLabel(self.splitter_4)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.splitter_4)
        self.label_2.setObjectName("label_2")
        self.tabWidget.addTab(self.tab_filters, "")
        self.tab_histograms = QtWidgets.QWidget()
        self.tab_histograms.setObjectName("tab_histograms")
        self.layoutWidget5 = QtWidgets.QWidget(self.tab_histograms)
        self.layoutWidget5.setGeometry(QtCore.QRect(270, 20, 741, 591))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget5)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_histograms_input = QtWidgets.QLabel(self.layoutWidget5)
        self.label_histograms_input.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_input.setObjectName("label_histograms_input")
        self.gridLayout.addWidget(self.label_histograms_input, 0, 0, 1, 1)
        self.label_histograms_output = QtWidgets.QLabel(self.layoutWidget5)
        self.label_histograms_output.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_output.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_output.setObjectName("label_histograms_output")
        self.gridLayout.addWidget(self.label_histograms_output, 0, 1, 1, 1)
        self.label_histograms_hinput = QtWidgets.QLabel(self.layoutWidget5)
        self.label_histograms_hinput.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_hinput.setTextFormat(QtCore.Qt.PlainText)
        self.label_histograms_hinput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_hinput.setObjectName("label_histograms_hinput")
        self.gridLayout.addWidget(self.label_histograms_hinput, 1, 0, 1, 1)
        self.label_histograms_houtput = QtWidgets.QLabel(self.layoutWidget5)
        self.label_histograms_houtput.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_houtput.setTextFormat(QtCore.Qt.PlainText)
        self.label_histograms_houtput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_houtput.setObjectName("label_histograms_houtput")
        self.gridLayout.addWidget(self.label_histograms_houtput, 1, 1, 1, 1)
        self.splitter_5 = QtWidgets.QSplitter(self.tab_histograms)
        self.splitter_5.setGeometry(QtCore.QRect(20, 30, 191, 141))
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName("splitter_5")
        self.pushButton_histograms_load = QtWidgets.QPushButton(self.splitter_5)
        self.pushButton_histograms_load.setObjectName("pushButton_histograms_load")
        self.label_11 = QtWidgets.QLabel(self.splitter_5)
        self.label_11.setObjectName("label_11")
        self.label_10 = QtWidgets.QLabel(self.splitter_5)
        self.label_10.setObjectName("label_10")
        self.splitter_6 = QtWidgets.QSplitter(self.tab_histograms)
        self.splitter_6.setGeometry(QtCore.QRect(20, 220, 191, 131))
        self.splitter_6.setOrientation(QtCore.Qt.Vertical)
        self.splitter_6.setObjectName("splitter_6")
        self.pushButton_Auto_global_thershold = QtWidgets.QPushButton(self.splitter_6)
        self.pushButton_Auto_global_thershold.setObjectName("pushButton_Auto_global_thershold")
        self.pushButton_globalThershold = QtWidgets.QPushButton(self.splitter_6)
        self.pushButton_globalThershold.setObjectName("pushButton_globalThershold")
        self.doubleSpinBox_Thershold_value = QtWidgets.QDoubleSpinBox(self.splitter_6)
        self.doubleSpinBox_Thershold_value.setMaximum(1.0)
        self.doubleSpinBox_Thershold_value.setSingleStep(0.01)
        self.doubleSpinBox_Thershold_value.setProperty("value", 0.5)
        self.doubleSpinBox_Thershold_value.setObjectName("doubleSpinBox_Thershold_value")
        self.splitter_7 = QtWidgets.QSplitter(self.tab_histograms)
        self.splitter_7.setGeometry(QtCore.QRect(30, 410, 171, 131))
        self.splitter_7.setOrientation(QtCore.Qt.Vertical)
        self.splitter_7.setObjectName("splitter_7")
        self.pushButton_local_thershold = QtWidgets.QPushButton(self.splitter_7)
        self.pushButton_local_thershold.setObjectName("pushButton_local_thershold")
        self.comboBox_thersholding_filter = QtWidgets.QComboBox(self.splitter_7)
        self.comboBox_thersholding_filter.setObjectName("comboBox_thersholding_filter")
        self.comboBox_thersholding_filter.addItem("")
        self.comboBox_thersholding_filter.addItem("")
        self.comboBox_thersholding_filter.addItem("")
        self.spinBox_thershlod_filter_size = QtWidgets.QSpinBox(self.splitter_7)
        self.spinBox_thershlod_filter_size.setMinimum(3)
        self.spinBox_thershlod_filter_size.setMaximum(41)
        self.spinBox_thershlod_filter_size.setSingleStep(2)
        self.spinBox_thershlod_filter_size.setProperty("value", 7)
        self.spinBox_thershlod_filter_size.setObjectName("spinBox_thershlod_filter_size")
        self.tabWidget.addTab(self.tab_histograms, "")
        self.tab_hybrid = QtWidgets.QWidget()
        self.tab_hybrid.setObjectName("tab_hybrid")
        self.label_histograms_output_2 = QtWidgets.QLabel(self.tab_hybrid)
        self.label_histograms_output_2.setGeometry(QtCore.QRect(630, 20, 401, 361))
        self.label_histograms_output_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_output_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_output_2.setObjectName("label_histograms_output_2")
        self.splitter = QtWidgets.QSplitter(self.tab_hybrid)
        self.splitter.setGeometry(QtCore.QRect(660, 410, 151, 111))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget6 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.doubleSpinBox_alpha = QtWidgets.QDoubleSpinBox(self.layoutWidget6)
        self.doubleSpinBox_alpha.setMinimum(0.1)
        self.doubleSpinBox_alpha.setMaximum(0.9)
        self.doubleSpinBox_alpha.setSingleStep(0.05)
        self.doubleSpinBox_alpha.setProperty("value", 0.5)
        self.doubleSpinBox_alpha.setObjectName("doubleSpinBox_alpha")
        self.horizontalLayout_6.addWidget(self.doubleSpinBox_alpha)
        self.pushButton_histograms_load_4 = QtWidgets.QPushButton(self.splitter)
        self.pushButton_histograms_load_4.setObjectName("pushButton_histograms_load_4")
        self.splitter_8 = QtWidgets.QSplitter(self.tab_hybrid)
        self.splitter_8.setGeometry(QtCore.QRect(10, 110, 161, 131))
        self.splitter_8.setOrientation(QtCore.Qt.Vertical)
        self.splitter_8.setObjectName("splitter_8")
        self.pushButton_histograms_load_2 = QtWidgets.QPushButton(self.splitter_8)
        self.pushButton_histograms_load_2.setObjectName("pushButton_histograms_load_2")
        self.label_12 = QtWidgets.QLabel(self.splitter_8)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.splitter_8)
        self.label_13.setObjectName("label_13")
        self.splitter_9 = QtWidgets.QSplitter(self.tab_hybrid)
        self.splitter_9.setGeometry(QtCore.QRect(10, 360, 161, 131))
        self.splitter_9.setOrientation(QtCore.Qt.Vertical)
        self.splitter_9.setObjectName("splitter_9")
        self.pushButton_histograms_load_3 = QtWidgets.QPushButton(self.splitter_9)
        self.pushButton_histograms_load_3.setObjectName("pushButton_histograms_load_3")
        self.label_15 = QtWidgets.QLabel(self.splitter_9)
        self.label_15.setObjectName("label_15")
        self.label_14 = QtWidgets.QLabel(self.splitter_9)
        self.label_14.setObjectName("label_14")
        self.splitter_2 = QtWidgets.QSplitter(self.tab_hybrid)
        self.splitter_2.setGeometry(QtCore.QRect(850, 420, 171, 91))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.label_9 = QtWidgets.QLabel(self.splitter_2)
        self.label_9.setObjectName("label_9")
        self.comboBox_hybrid = QtWidgets.QComboBox(self.splitter_2)
        self.comboBox_hybrid.setEnabled(True)
        self.comboBox_hybrid.setObjectName("comboBox_hybrid")
        self.comboBox_hybrid.addItem("")
        self.comboBox_hybrid.addItem("")
        self.comboBox_hybrid.addItem("")
        self.comboBox_hybrid.addItem("")
        self.comboBox_hybrid.addItem("")
        self.splitter_12 = QtWidgets.QSplitter(self.tab_hybrid)
        self.splitter_12.setGeometry(QtCore.QRect(191, 21, 421, 591))
        self.splitter_12.setOrientation(QtCore.Qt.Vertical)
        self.splitter_12.setObjectName("splitter_12")
        self.label_histograms_input_2 = QtWidgets.QLabel(self.splitter_12)
        self.label_histograms_input_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_input_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_input_2.setObjectName("label_histograms_input_2")
        self.label_histograms_hinput_2 = QtWidgets.QLabel(self.splitter_12)
        self.label_histograms_hinput_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_hinput_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_histograms_hinput_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_hinput_2.setObjectName("label_histograms_hinput_2")
        self.tabWidget.addTab(self.tab_hybrid, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.splitter_3 = QtWidgets.QSplitter(self.tab)
        self.splitter_3.setGeometry(QtCore.QRect(20, 110, 151, 141))
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.pushButton_frequency_load = QtWidgets.QPushButton(self.splitter_3)
        self.pushButton_frequency_load.setObjectName("pushButton_frequency_load")
        self.label_18 = QtWidgets.QLabel(self.splitter_3)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.splitter_3)
        self.label_19.setObjectName("label_19")
        self.splitter_10 = QtWidgets.QSplitter(self.tab)
        self.splitter_10.setGeometry(QtCore.QRect(190, 90, 821, 411))
        self.splitter_10.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_10.setObjectName("splitter_10")
        self.label_pass_input = QtWidgets.QLabel(self.splitter_10)
        self.label_pass_input.setFrameShape(QtWidgets.QFrame.Box)
        self.label_pass_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_pass_input.setObjectName("label_pass_input")
        self.label_pass_output = QtWidgets.QLabel(self.splitter_10)
        self.label_pass_output.setFrameShape(QtWidgets.QFrame.Box)
        self.label_pass_output.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_pass_output.setObjectName("label_pass_output")
        self.splitter_11 = QtWidgets.QSplitter(self.tab)
        self.splitter_11.setGeometry(QtCore.QRect(30, 320, 131, 91))
        self.splitter_11.setOrientation(QtCore.Qt.Vertical)
        self.splitter_11.setObjectName("splitter_11")
        self.label_20 = QtWidgets.QLabel(self.splitter_11)
        self.label_20.setObjectName("label_20")
        self.comboBox_pass_filter = QtWidgets.QComboBox(self.splitter_11)
        self.comboBox_pass_filter.setObjectName("comboBox_pass_filter")
        self.comboBox_pass_filter.addItem("")
        self.comboBox_pass_filter.addItem("")
        self.comboBox_pass_filter.addItem("")
        self.tabWidget.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1069, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Filter Settings"))
        self.label_3.setText(_translate("MainWindow", "Select Filter"))
        self.comboBox_filters.setItemText(0, _translate("MainWindow", "Tab to Select"))
        self.comboBox_filters.setItemText(1, _translate("MainWindow", "Gaussian noise"))
        self.comboBox_filters.setItemText(2, _translate("MainWindow", "Uniform noise"))
        self.comboBox_filters.setItemText(3, _translate("MainWindow", "Salt & pepper noise"))
        self.comboBox_filters.setItemText(4, _translate("MainWindow", "Gaussian filter"))
        self.comboBox_filters.setItemText(5, _translate("MainWindow", "Median filter"))
        self.comboBox_filters.setItemText(6, _translate("MainWindow", "Average filter"))
        self.comboBox_filters.setItemText(7, _translate("MainWindow", "Sobel ED"))
        self.comboBox_filters.setItemText(8, _translate("MainWindow", "Roberts ED"))
        self.comboBox_filters.setItemText(9, _translate("MainWindow", "Prewitt ED"))
        self.comboBox_filters.setItemText(10, _translate("MainWindow", "Canny ED"))
        self.comboBox_filters.setItemText(11, _translate("MainWindow", "Laplacian of Gaussian"))
        self.comboBox_filters.setItemText(12, _translate("MainWindow", "Laplacian1"))
        self.comboBox_filters.setItemText(13, _translate("MainWindow", "Laplacian2"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Additional Parameters"))
        self.label_4.setText(_translate("MainWindow", "filter size"))
        self.label_5.setText(_translate("MainWindow", "sigma"))
        self.label_6.setText(_translate("MainWindow", "mu"))
        self.label_7.setText(_translate("MainWindow", "low"))
        self.label_filters_input.setText(_translate("MainWindow", "Input image"))
        self.label_filters_output.setText(_translate("MainWindow", "Output image"))
        self.pushButton_filters_load.setText(_translate("MainWindow", "Load Image"))
        self.label.setText(_translate("MainWindow", "Name:"))
        self.label_2.setText(_translate("MainWindow", "Size:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_filters), _translate("MainWindow", "Filters"))
        self.label_histograms_input.setText(_translate("MainWindow", "Input image"))
        self.label_histograms_output.setText(_translate("MainWindow", "Output image"))
        self.label_histograms_hinput.setText(_translate("MainWindow", "Input Histogram"))
        self.label_histograms_houtput.setText(_translate("MainWindow", "Output Histogram"))
        self.pushButton_histograms_load.setText(_translate("MainWindow", "Load image"))
        self.label_11.setText(_translate("MainWindow", "Name:"))
        self.label_10.setText(_translate("MainWindow", "Size:"))
        self.pushButton_Auto_global_thershold.setText(_translate("MainWindow", "Auto Global Thersholding"))
        self.pushButton_globalThershold.setText(_translate("MainWindow", "Global Thersholding"))
        self.pushButton_local_thershold.setText(_translate("MainWindow", "Local Thersholding"))
        self.comboBox_thersholding_filter.setItemText(0, _translate("MainWindow", "Gaussian"))
        self.comboBox_thersholding_filter.setItemText(1, _translate("MainWindow", "Average"))
        self.comboBox_thersholding_filter.setItemText(2, _translate("MainWindow", "Median"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_histograms), _translate("MainWindow", "Histograms"))
        self.label_histograms_output_2.setText(_translate("MainWindow", "Output image"))
        self.label_8.setText(_translate("MainWindow", "Alpha"))
        self.pushButton_histograms_load_4.setText(_translate("MainWindow", "Make Hybrid"))
        self.pushButton_histograms_load_2.setText(_translate("MainWindow", "Load image A"))
        self.label_12.setText(_translate("MainWindow", "Name:"))
        self.label_13.setText(_translate("MainWindow", "Size:"))
        self.pushButton_histograms_load_3.setText(_translate("MainWindow", "Load image B"))
        self.label_15.setText(_translate("MainWindow", "Name:"))
        self.label_14.setText(_translate("MainWindow", "Size:"))
        self.label_9.setText(_translate("MainWindow", "Select Filter Type"))
        self.comboBox_hybrid.setItemText(0, _translate("MainWindow", "lp1"))
        self.comboBox_hybrid.setItemText(1, _translate("MainWindow", "lp2"))
        self.comboBox_hybrid.setItemText(2, _translate("MainWindow", "sobel"))
        self.comboBox_hybrid.setItemText(3, _translate("MainWindow", "prewitt"))
        self.comboBox_hybrid.setItemText(4, _translate("MainWindow", "roberts"))
        self.label_histograms_input_2.setText(_translate("MainWindow", "Input image A"))
        self.label_histograms_hinput_2.setText(_translate("MainWindow", "Input image B"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_hybrid), _translate("MainWindow", "Hybrid"))
        self.pushButton_frequency_load.setText(_translate("MainWindow", "Load Image"))
        self.label_18.setText(_translate("MainWindow", "Name:"))
        self.label_19.setText(_translate("MainWindow", "Size:"))
        self.label_pass_input.setText(_translate("MainWindow", "input image"))
        self.label_pass_output.setText(_translate("MainWindow", "Fourier image"))
        self.label_20.setText(_translate("MainWindow", "Select Pass Filter"))
        self.comboBox_pass_filter.setItemText(0, _translate("MainWindow", "Tab to select"))
        self.comboBox_pass_filter.setItemText(1, _translate("MainWindow", "Low pass"))
        self.comboBox_pass_filter.setItemText(2, _translate("MainWindow", "High pass"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Frequency"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
